# .github/workflows/git-sync.yml

on: push
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync-branch
        uses: wei/git-sync@v3
        with:
          source_repo: ${{secrets.SOURCE_REPO}}
          source_branch: "refs/remotes/source/*"
          destination_repo: ${{secrets.DESTINATION_REPO}}
          destination_branch: "refs/heads/*"
      - name: git-sync-tag
        uses: wei/git-sync@v3
        with:
          source_repo: ${{secrets.SOURCE_REPO}}
          source_branch: "refs/tags/*"
          destination_repo: ${{secrets.DESTINATION_REPO}}
          destination_branch: "refs/tags/*"